service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-aws-documentation
provider:
  name: aws
  runtime: nodejs8.10

functions:
  resolver:
    handler: functions/resolver/Handler.main
    events:
      - http:
          cors: 
            origin: 'https://compose.mixmax.com'
          method: get
          path: resolver
       
  typeahead:
      handler: functions/typeahead/Handler.main
      events:
        - http:
            cors: 
              origin: 'https://compose.mixmax.com'
            method: get
            path: typeahead
custom:
  documentation:
    info:
      version: "2" # see note above about this being ignored
      title: "Name of your API" # see note above about this being ignored
      description: "This is the best API ever"
      termsOfService: "http://www.example.com/terms-of-service"
      contact:
        name: "John Smith"
        url: "http://www.example.com/me"
        email: "js@example.com"
      license:
        name: "Licensing"
        url: "http://www.example.com/licensing"
    tags:
      -
        name: "Data Creation"
        description: "Services to create things"
      -
        name: "Some other tag"
        description: "A tag for other things"
    authorizers:
      -
        name: "MyCustomAuthorizer"
        description: "This is an error"
    resources:
      -
        path: "some/path"
        description: "This is the description for some/path"
      -
        path: "some/other/path"
        description: "This is the description for some/other/path"
