service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs8.10

functions:
  resolver:
    handler: functions/resolver/Handler.hello
    events:
      - http:
          cors: 
            origin: 'https://compose.mixmax.com'
          method: get
          path: resolver

  typeahead:
      handler: functions/typeahead/Handler.hello
      events:
        - http:
            cors: 
              origin: 'https://compose.mixmax.com'
            method: get
            path: typeahead
